###############################---端口---##############################
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://10.1.15.101:3306/HTTestMember?serverTimezone=GMT%2B8&&useUnicode=true&characterEncoding=UTF8
    username: root
    password: soltrip40061