###############################---端口---##############################
server:
  port: 8080
###############################---DB---##############################
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/pingtai?useUnicode=true&characterEncoding=UTF8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:root}